export const tipoIdentidad = [
    { value: "CC", nombre: "Cédula de Ciudadanía" },

    { value: "TI", nombre: "Tarjeta de Identidad" },
    { value: "CE", nombre: "Cédula de Extranjería" },
];
export const Departamentos = [
    { nombre: "Antioquia" },
    { nombre: "Atlántico" },
    { nombre: "Bogotá, D.C." },
    { nombre: "Bolívar" },
    { nombre: "Boyacá" },
    { nombre: "Caldas" },
    { nombre: "Caquetá" },
    { nombre: "Cauca" },
    { nombre: "Cesar" },
    { nombre: "Córdoba" },
    { nombre: "Cundinamarca" },
    { nombre: "Chocó" },
    { nombre: "Huila" },
    { nombre: "La Guajira" },
    { nombre: "Magdalena" },
    { nombre: "Meta" },
    { nombre: "Nariño" },
    { nombre: "Norte de Santander" },
    { nombre: "Quindío" },
    { nombre: "Risaralda" },
    { nombre: "Santander" },
    { nombre: "Sucre" },
    { nombre: "Tolima" },
    { nombre: "Valle del Cauca" },
    { nombre: "Arauca" },
    { nombre: "Casanare" },
    { nombre: "Putumayo" },
    { nombre: "San Andrés, Providencia y Santa Catalina" },
    { nombre: "Amazonas" },
    { nombre: "Guainía" },
    { nombre: "Guaviare" },
    { nombre: "Vaupés" },
    { nombre: "Vichada" }
]
